const main = async (params) => {
  params = params.split("_")
  let network = params[0]
  let address = params[1]
  let chain =  (network == "ETHEREUM") ? "MAINNET" : (network + "_MAINNET")
  console.log(network, chain)

  const payload = JSON.stringify({
    query: `query CollectionInfo {
    tokens(networks: [{network: `+network+`, chain: `+chain+`}],

      pagination: {limit: 40},
      where: {collectionAddresses: "`+address+`"})
    { nodes { 
      token{
        name 
        description
        tokenId
        collectionName
        image {
          url
          mimeType
          size
        }
      }

    }
      pageInfo { hasNextPage }
      
    }
  }`,
  })

  const response = await fetch(
    'https://api.zora.co/graphql',
    {
      method: 'post',
      body: payload,
      headers: {
        'Content-Type': 'application/json',
      },
    }
  )
  const data = await response.json()
  
  let source = `<!doctype html>
<html><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NFT collection album</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
</head><body><main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">NFT collection album</h1>
        <p class="lead text-body-secondary">This webpage is generated by Fleek Network serverless function.</p>        
      </div>
    </div>
  </section>
  <div class="album py-5 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">`
  
  let tokens = data['data']['tokens']['nodes']
  
  for (let i=0; i<tokens.length; ++i){
    let token = tokens[i]['token']
    image_url = token['image']['url']
    let token_name = token['name']
    let description = token['description']
    let token_id = token['tokenId']
    if (image_url.startsWith("ipfs://"))
      image_url = "https://cloudflare-ipfs.com/ipfs/" + image_url.substr("ipfs://".length-1)
    else if (image_url.startsWith("ar://"))
      image_url = "https://arweave.net/" + image_url.substr("ar://".length-1)

      source += `<div class="col">
          <div class="card shadow-sm">
            <img src="`+image_url+`">
            <div class="card-body">
              <p class="card-text">`+description+`</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a type="button" href="`+image_url+`" target="_new" class="btn btn-sm btn-outline-secondary">View</a>
                  <a type="button" href="https://opensea.io/assets/`+network+`/`+address+`/`+token_id+ `" target="_new" class="btn btn-sm btn-outline-secondary">Buy</a>
                </div>                
              </div>
            </div>
          </div>
        </div>`
  }
  
  source += `</div></div></div></main>
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1"><a href="#">Back to top</a></p>
    <p class="mb-1">NFT collection album example generated by Fleek Network serverless function</p>
    <p class="mb-0">Visit <a href="https://fleek.network/">Fleek Network homepage</a> and <a href="https://docs.fleek.network/docs/learn/introduction/">read documentation</a>.</p>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"  crossorigin="anonymous"></script>
</body></html>`

  return source
}
